### ISSUE TITLE
about performance

### ISSUE THREAD

**Issue by 738654805** [FunkyKoki/Look_At_Boundary_PyTorch#2]
The performance on the 300W is not as good as the results in the paper. The best result i got is about 5.1NME (inter-pupil) on the 300W.  Do you have some suggestions? Thx in advance.

**Comment by guoguoguilai** [comment]
> The performance on the 300W is not as good as the results in the paper. The best result i got is about 5.1NME (inter-pupil) on the 300W. Do you have some suggestions? Thx in advance.
Did you use the code that @FunkyKoki  provided?

**Comment by 738654805** [comment]
@guoguoguilai I just use the boundary heatmaps re-implement by myself, it seems not work on the 300W.

**Comment by FunkyKoki** [comment]
Not very well on 300W as well, but better on WFLW(at least close to the result the author gave), later, I would try AFLW and COFW.
The performance would be reported in about one month.
Thanks for your concern...
